### ISSUE TITLE
Preparing an automatic migration of mySQL database to duckDB

### ISSUE THREAD

**Issue by PiechZ** [PiechZ/ADK_wrapped#9]
(edited by @shippy)

- [x] Set up a MariaDB (open-source MySQL) container that loads the provided SQL dump as-is (Windows-1250, ...) 
- [x] Set up a Meltano MariaDB extractor in another container that reads the relevant tables
- [x] Optional: set up a Meltano transformer that runs the dbt models in ´sql_prep/`
- [x] Set up a Meltano DuckDB loader that saves the relevant data in a `duckdb` file
- [ ] Optional: directly upload the DuckDB file to S3

**Comment by shippy** [comment]
Updated the description with substeps.

**Comment by shippy** [comment]
Accomplished by [`greybox-mysql2duck`](https://github.com/shippy/greybox-mysql2duck).
